lights: Move version above fqname
system/libvintf/xsd/halManifest/vts/ValidateHalManifest.cpp:76: Failure
XML is not valid according to the xsd
While validating: (dir_path + "/"s + file_name).c_str()
Which is: /vendor/etc/vintf/manifest/android.hardware.lights-service.tangorpro.xml
Against the schema: xsd
Which is: /data/local/tmp/hal_manifest.xsd
Libxml2 errors:
Error: Element 'version': This element is not expected. Expected is ( fqname ).

Bug: 245442303
Test: Function works as expected
Change-Id: I51c94c509271caa13cd5e7b97c11a3ed866e4e95